# PowerUp

TARGET = _pup
TARGETEXTENSION = 

CC = vc +powerup
CCOUT = -o=
COPTS = -c -c99 -DAMIGA -O1 $(OUTFMTS)

LD = $(CC)
LDOUT = $(CCOUT)
LDFLAGS = -lm -lamiga

RM = delete force quiet

include make.rules
