  "illegal operand",ERROR,
  "word register expected",ERROR,
  "",ERROR,
  "value does not find in %d bits",WARNING,
  "data size not supported",ERROR,
  "illegal use of SOF",WARNING,
  "illegal use of SEG",WARNING,
  "illegal use of DPP prefix",WARNING,
