  "syntax error",ERROR,
  "invalid extension",ERROR,
  "no space before operands",WARNING,
  "too many closing parentheses",WARNING,
  "missing closing parentheses",WARNING,
  "missing operand",ERROR,                                           /* 5 */
  "garbage at end of line",WARNING,
  "%c expected",WARNING,
  "invalid data operand",ERROR,
  ", expected",WARNING,
  "identifier expected",ERROR,                                       /* 10 */
  "invalid numeric expansion",ERROR,
  "unexpected \"%s\" without \"%s\"",ERROR,
  "dsect already active",ERROR,
  "dend without dsect",ERROR,
  "missing dend",ERROR,                                              /* 15 */
  "maximum inline nesting depth exceeded (%d)",ERROR,
  "einline without inline",ERROR,
  "",ERROR,
  "",ERROR,
  "",WARNING,                                                        /* 20 */
  "alignment too big",WARNING,
  "label <%s> has already been defined",WARNING,
  "skipping instruction in struct init",WARNING,
  "last %d bytes of string constant have been cut",WARNING,
